#!/bin/bash
# =============================================================
#  Network Configuration Helper — Run on EACH VM
#  Sets static IPs on the VMware Host-Only network
#  FYP: Prevention of DDoS Attacks with Virtualization
#  Author: Oladeji Ibrahim Olaleye | U22CYS1103
# =============================================================
# Usage: sudo bash network_config.sh <vm_role>
# Roles: target | backup | attacker | controller

ROLE=${1:-target}
IFACE=$(ip -o link show | grep -v lo | awk '{print $2}' | tr -d ':' | head -1)
GATEWAY="192.168.100.1"

case "$ROLE" in
  target)     IP="192.168.100.10" ;;
  backup)     IP="192.168.100.20" ;;
  attacker)   IP="192.168.100.30" ;;
  controller) IP="192.168.100.40" ;;
  *)
    echo "Unknown role: $ROLE"
    echo "Usage: $0 [target|backup|attacker|controller]"
    exit 1
    ;;
esac

echo "[INFO] Configuring $ROLE VM: IP=$IP on $IFACE"

# ── Debian 12 (uses /etc/network/interfaces) ─────────────────
cat > /etc/network/interfaces << EOF
# This file was generated by network_config.sh
# FYP: DDoS Prevention with Virtualization

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $IFACE
iface $IFACE inet static
    address $IP
    netmask 255.255.255.0
    gateway $GATEWAY
    dns-nameservers 8.8.8.8 1.1.1.1
EOF

# Apply
ifdown "$IFACE" 2>/dev/null; ifup "$IFACE"

echo "[OK] IP configured: $IP"
echo ""
echo "VM Network Map:"
echo "  VM1 Target     : 192.168.100.10"
echo "  VM2 Backup     : 192.168.100.20"
echo "  VM3 Attacker   : 192.168.100.30"
echo "  VM4 Controller : 192.168.100.40"
echo "  Gateway        : 192.168.100.1"
echo ""
echo "VMware: Use Host-Only network adapter (VMnet1) for ALL VMs."
echo "        This ensures isolation from the host and internet."
